### ISSUE TITLE
Installation using Cluster addon fails in kyma 1.14-rc1

### ISSUE THREAD

**Issue by valentinvieriu** [SAP-samples/xf-application-mocks#23]
With a fresh installation of Kyma 1.14-rc1 adding `github.com/sap/xf-addons//addons/index.yaml?ref=latest` and then adding it as an instance to your namespace fails.
![image](https://user-images.githubusercontent.com/478866/88172545-75c42f80-cc21-11ea-829b-84df526eefe2.png)

**Comment by a-thaler** [comment]
Not a supported scenario anymore
