### ISSUE TITLE
xf.yaml

### ISSUE THREAD

**Issue by mchcn2018** [SAP-samples/xf-application-mocks#35]
xf.yaml (old name) = kyma.yaml (new name)?
If it is a case, please update the tutorial Deploy Commerce Mock Application in the Kyma Runtime -> Step 2: Apply resources to Kyma runtime accordingly: https://developers.sap.com/tutorials/cp-kyma-mocks.html

**Comment by jcawley5** [comment]
Thanks for the feedback, changed was pushed to qa and will be moved to prod on next refresh.
